const firstname =  prompt('what is your name?');
console.log(firstname);
const surname =  prompt('what is your surname?');
console.log(surname);
const age =  prompt('how old are you?');
console.log(age);
const hobby =  prompt('what is your hobby?');
console.log(hobby);
const from =  prompt('where are you from?');
console.log(from);
const university =  prompt('where dou you study?');
console.log(university);
const data =  prompt('when is your birthday?');
console.log(data);
const height =  prompt('how tall are you?');
console.log(height);
const fructis =  prompt('which fruit do you like?');
console.log(fructis);
const job =  prompt('What job are you interested in?');
console.log(job); 